# Commands to start on workspace startup
workspaceLocation: laraboot-jetstream-demo/src
tasks:
  - name: Install cli
    openMode: tab-after
    init: npm i -g @laraboot-io/cli
    command: |
      laraboot --version
      cd /workspace/laraboot-jetstream-demo/src
      chmod -R +x ./scripts
      ./scripts/build.sh
      cd jetstream-demo-8.0
      laraboot run --port=9000
# Ports to expose on workspace startup
ports:
  - port: 9000
    onOpen: open-preview
